### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by D1abloRUS** [D1abloRUS/go-check#2]
~~- [ ] вынос метода sentSlack из main.go~~
- [x] отредактировать flags:

~~1. Исправить типы, где требуется~~
~~2. Добавить короткие флаги, типо -h -p~~
~~3. Добавить проверки на обязательные флаги~~
~~4. Исправить имена флагов, описание, значение по умолчанию~~

- [x] написать тесты к функциям

**Comment by D1abloRUS** [comment]
- [ ]

**Comment by merabpyh** [comment]
представьте весь ожидаемый список флагов пожалуйста, типа:
-f указать файл c url 
-h --help для справки
-v показать версию

**Comment by D1abloRUS** [comment]
-h = host
-p = port
-i = interval
Остальные можно пока, не сокращать

**Comment by D1abloRUS** [comment]
done
